env:
    MANIFEST: https://github.com/Project-Xtended/manifest.git -b xt
    DEVICE: sweet
    OEM: xiaomi
    DT_LINK: https://github.com/Imranp0pz/device_xiaomi_sweet.git
    DT_PATH: device/$OEM/$DEVICE
    PLATFORM: sm6250
    TARGET: xtended
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: xtended_${DEVICE}-userdebug
    OUTPUT: X*sweet*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G


  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work      - repo init --depth=1 --no-repo-verify -u $MANIFEST  -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - git clone $DT_LINK $DT_PATH
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"


  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch "$LUNCH_COMBO"
      - mka -j31 $TARGET
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        

